### ISSUE TITLE
Windows ist resizable but content will neither scale nor move. 

### ISSUE THREAD

**Issue by solddrem** [ComputerElite/QSE#1]
The window shouldnt be of type resizeable. Maybe it should be a tool window.

https://docs.microsoft.com/de-de/dotnet/api/system.windows.window.windowstyle?view=netcore-3.1

**Comment by ComputerElite** [comment]
Hi @solddrem I'm working on it. Thanks.

**Comment by ComputerElite** [comment]
I haven't changed the Window Type. I'll change the ResizeMode to "CanMinimize". So you can minimize the Window.

**Comment by ComputerElite** [comment]
Done.

**Comment by solddrem** [comment]
Thank u for updating the Program

**Comment by ComputerElite** [comment]
You're welcome 🤗
